"use strict";
angular.module('creamApp')

.constant(
		'USER_ROLES',
		[ 'ROLE_USER', 'ROLE_ADMIN', 'ROLE_DIRECTEUR', 'ROLE_DIRECTEUR_RESEAU',
				'ROLE_MANAGER_COMMERCIAL', 'ROLE_AGENT', 'ROLE_GESTIONNAIRE' , 'ROLE_QUALIF' ]);
